CREATE TABLE States (
    StateID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StateName NVARCHAR2(100)
); 

CREATE TABLE ATE (
    ATEID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AreaName NVARCHAR2(100),
    StateID_ATE NUMBER,
    FOREIGN KEY (StateID_ATE) REFERENCES States(StateID)
);

CREATE TABLE Cities (
    CityID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CityName NVARCHAR2(100),
    ATEID NUMBER,
    FOREIGN KEY (ATEID) REFERENCES ATE(ATEID)
);

CREATE TABLE Addresses (
    AddressID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Street NVARCHAR2(255),
    CityID NUMBER,
    ZipCode NVARCHAR2(10),
    FOREIGN KEY (CityID) REFERENCES Cities(CityID)
);

CREATE TABLE Manufacturer (
    ManufacturerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ManufacturerName NVARCHAR2(100),
    ContactInfo NVARCHAR2(255)
);

CREATE TABLE Equipment (
    EquipmentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EquipmentName NVARCHAR2(100) NOT NULL,
    Description NVARCHAR2(255),
    RentalCost NUMBER NOT NULL,
    RentalRate NUMBER(10, 2) DEFAULT 0.0,
    ManufacturerID NUMBER,
    AvailableOnStock NUMBER,
    BaseRentalTime NUMBER DEFAULT 7,
    FOREIGN KEY (ManufacturerID) REFERENCES Manufacturer(ManufacturerID)
);

CREATE TABLE Clients (
    ClientID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL,
    PhoneNumber NVARCHAR2(15),
    Email NVARCHAR2(50),
    AddressID NUMBER,
    FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);

ALTER TABLE Clients
ADD CONSTRAINT CK_PhoneNumberFormat CHECK (
    REGEXP_LIKE(PhoneNumber, '^\+7[0-9]{10}$') OR 
    REGEXP_LIKE(PhoneNumber, '^\+375[0-9]{9}$') OR 
    REGEXP_LIKE(PhoneNumber, '^\+7[0-9]{3}-[0-9]{7}$') OR
    REGEXP_LIKE(PhoneNumber, '^\+375[0-9]{3}-[0-9]{7}$')
);

ALTER TABLE Clients
ADD CONSTRAINT CK_Client_EmailFormat CHECK (
    REGEXP_LIKE(Email, '.+@.+\..+')
);

CREATE TABLE RentalStates (
    RentalStateID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StateName NVARCHAR2(100),
    StateCounter NUMBER
); 

CREATE TABLE Employees (
    EmployeesID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL,
    PhoneNumber NVARCHAR2(15),
    Email NVARCHAR2(50) UNIQUE,
    CityID NUMBER,
    FOREIGN KEY (CityID) REFERENCES Cities(CityID)
);

ALTER TABLE Employees
ADD CONSTRAINT CK_EMP_PhoneNumberFormat CHECK (
    REGEXP_LIKE(PhoneNumber, '^\+7[0-9]{10}$') OR 
    REGEXP_LIKE(PhoneNumber, '^\+375[0-9]{9}$') OR 
    REGEXP_LIKE(PhoneNumber, '^\+7[0-9]{3}-[0-9]{7}$') OR
    REGEXP_LIKE(PhoneNumber, '^\+375[0-9]{3}-[0-9]{7}$')
);

ALTER TABLE Employees
ADD CONSTRAINT CK_Employee_EmailFormat CHECK (
    REGEXP_LIKE(Email, '.+@.+\..+')
);

CREATE TABLE Masters (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NumberOfCompletedRentals NUMBER DEFAULT '0',
    NumberOfReturnedRentals NUMBER DEFAULT '0',
    MastersRating NUMBER DEFAULT '0',
    EmployeesId NUMBER,
    ManufacturerID NUMBER,
    FOREIGN KEY(EmployeesId) REFERENCES Employees(EmployeesID),
    FOREIGN KEY(ManufacturerID) REFERENCES Manufacturer(ManufacturerID)
);

CREATE TABLE Rentals (
    RentalID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID NUMBER,
    EmployeeID NUMBER,
    EquipmentID NUMBER,
    RentalStateID NUMBER,
    RentalStartDate TIMESTAMP(6) NOT NULL,
    RentalEndDate TIMESTAMP(6) NOT NULL,
    RentalExtensionDate TIMESTAMP(6),
    TotalCost NUMBER(10, 2) NOT NULL,
    AddressID NUMBER,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID),
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeesID),
    FOREIGN KEY (EquipmentID) REFERENCES Equipment(EquipmentID),
    FOREIGN KEY (RentalStateID) REFERENCES RentalStates(RentalStateID),
    FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);
